### ISSUE TITLE
Please add samples for  "Semantic Time support" in "Awareness APIs"

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [googlesamples/android-play-awareness#2]
This:
https://android-developers.googleblog.com/2017/06/semantic-time-support-now-available-on.html

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
